FROM openjdk:17-jdk-slim

WORKDIR /app

# 复制jar文件
COPY merchant-server/notification-service/target/notification-service-*.jar app.jar

# 暴露端口
EXPOSE 8084

# 启动应用
ENTRYPOINT ["java", "-jar", "/app/app.jar"]